name: example-start
on:
    push:
        branches:
            - cypress-example-start
jobs:
  start:
    # example with web application build,
    # server start and waiting for the server
    # to respond before running tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/start
          build: npm install typescript
          start: npm start
          wait-on: 'http://localhost:5000'
