name: example-webpack
on:
    push:
        branches:
            - cypress-example-webpack
jobs:
  wait:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/webpack
          start: npm start
          wait-on: 'http://localhost:8080'
